[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1b4df1cc40742669789edcf430eb11997593189d"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "b34e4969af08602d297a0c3cfcdf1b8e100061b9e55c84735782f50128464117"
    url = "https://github.com/jkozdon/PETSc_jll.jl/releases/download/PETSc-v3.15.1+0/PETSc.v3.15.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "8103999b56213b3daf9dd72abf34e8cbd3bc2266"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "0fadc991fd43843b33abe8a21c1d92a608853f45fe4138db976fe7b90ce3d6c4"
    url = "https://github.com/jkozdon/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
