[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "8103999b56213b3daf9dd72abf34e8cbd3bc2266"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "0fadc991fd43843b33abe8a21c1d92a608853f45fe4138db976fe7b90ce3d6c4"
    url = "https://github.com/jkozdon/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "7aae6bec73a21b9a4b1dcdbf27f3f3eebe04a6a5"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "63551299215e0d00a83bc6271168bba7f4c2f08cc71e045b069d57d9bf4df785"
    url = "https://github.com/jkozdon/PETSc_jll.jl/releases/download/PETSc-v3.15.2+1/PETSc.v3.15.2.x86_64-apple-darwin-libgfortran5.tar.gz"
