# Autogenerated wrapper script for PETSc_jll for x86_64-apple-darwin-libgfortran5
export libpetsc_Float32_Complex_Int32, libpetsc_Float32_Real_Int32, libpetsc_Float64_Real_Int64

using OpenBLAS32_jll
using MPICH_jll
using MicrosoftMPI_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PETSc")
JLLWrappers.@declare_library_product(libpetsc_Float32_Complex_Int32, "@rpath/libpetsc.3.15.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float32_Real_Int32, "@rpath/libpetsc.3.15.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64, "@rpath/libpetsc.3.15.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, MPICH_jll, MicrosoftMPI_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libpetsc_Float32_Complex_Int32,
        "lib/petsc/single_complex_Int32/lib/libpetsc.3.15.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Real_Int32,
        "lib/petsc/single_real_Int32/lib/libpetsc.3.15.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64,
        "lib/petsc/double_real_Int64/lib/libpetsc.3.15.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
